# Generated by Django 3.0.8 on 2020-07-20 06:58

from django.db import migrations
def create_data(apps, schema_editor):
    Student = apps.get_model('users', 'User')
    Student(name="Kshitij Raj Sharma", email="kshitij@wrc.edu.np", document="22342342", phone="9864488366").save()




class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_data),
    ]
