# Generated by Django 3.0.8 on 2020-07-30 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20200728_0752'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roi',
            old_name='geom',
            new_name='geometry',
        ),
        migrations.RenameField(
            model_name='roi_divided',
            old_name='geom',
            new_name='geometry',
        ),
    ]
