# Generated by Django 3.0.8 on 2020-07-30 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20200730_0705'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roi',
            old_name='geometry',
            new_name='geom',
        ),
        migrations.RenameField(
            model_name='roi_divided',
            old_name='geometry',
            new_name='geom',
        ),
    ]
